services:
  - type: web
    name: corplink-messenger
    runtime: docker
    plan: starter
    envVars:
      - key: APP_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: corplink-postgres
          property: connectionString
      - key: TOKEN_TTL_SECONDS
        value: 86400
      - key: CORS_ORIGIN
        value: "*"
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: corplink-postgres
    plan: starter
